mysql:
  host: "localhost"
  user: "root"
  password: "*YOUR PASSWORD*"
  db: "ml_db"

paths:
  pdf_folder: "static/downloaded_pdfs"
  models_folder: "models"

selenium:
  driver_path: "/path/to/chromedriver"
  headless: true

genai:
  enabled: true

training:
  model_path: "models/xgb_model.joblib"
  scaler_path: "models/scaler.joblib"
  test_size: 0.2
  random_state: 42
